name: Code Quality
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install

      - name: Type Check
        run: yarn type-check

      - name: Eslint
        run: yarn lint

      - name: Create .env file
        run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: Test
        run: yarn test
