name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: yarn install

      - name: Build packages
        run: yarn turbo run build --filter=./packages/*

      - name: Test
        env:
          PORT: 4000
          ORIGIN_URL: http://localhost:4000
          FRONTEND_URL: http://localhost:3000
        run: yarn test
